### ISSUE TITLE
[Feature]: Support for mid-cycle splits of ScanImageTiff files

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/roiextractors#299]
### What would you like to see added to ROI Extractors?

Currently, the scanimage tiff imaging extractors assume that each file contains a full cycle of frames. Ex. for 2 channels, 2 planes, and 2 framesPerSlice:
        ```
        [channel_1_plane_1_frame_1, channel_2_plane_1_frame_1, channel_1_plane_1_frame_2, channel_2_plane_1_frame_2,
         channel_1_plane_2_frame_1, channel_2_plane_2_frame_1, channel_1_plane_2_frame_2, channel_2_plane_2_frame_2,
         channel_1_plane_1_frame_3, channel_2_plane_1_frame_3, channel_1_plane_1_frame_4, channel_2_plane_1_frame_4,
         channel_1_plane_2_frame_3, channel_2_plane_2_frame_3, channel_1_plane_2_frame_4, channel_2_plane_2_frame_4,
        ```
        ```
         ...
        ```
        ```
         channel_1_plane_1_frame_N, channel_2_plane_1_frame_N, channel_1_plane_2_frame_N, channel_2_plane_2_frame_N]
        ```
where the last frame of the file MUST BE `channel_2_plane_2_frame_N` for however many frames it has.

However, it is possible to split scanimage files mid-cycle based on a maximum number of frames. Ex. for 2 channels, 2 planes, 2 framesPerSlice AND a maximum total number of frames/file of 10:

File 1: `prefix_00001_00001.tif`
        ```
        [channel_1_plane_1_frame_1, channel_2_plane_1_frame_1, channel_1_plane_1_frame_2, channel_2_plane_1_frame_2,
         channel_1_plane_2_frame_1, channel_2_plane_2_frame_1, channel_1_plane_2_frame_2, channel_2_plane_2_frame_2,
         channel_1_plane_1_frame_3, channel_2_plane_1_frame_3]
        ```

File 2: `prefix_00001_00002.tif`
    ```
    [channel_1_plane_1_frame_4, channel_2_plane_1_frame_4,
     channel_1_plane_2_frame_3, channel_2_plane_2_frame_3, channel_1_plane_2_frame_4, channel_2_plane_2_frame_4]
    ```

The ScanImageTiffImagingExtractors should be able to accommodate this case.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/roiextractors/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/roiextractors/issues)?

**Comment by h-mayorquin** [comment]
This was fixed by https://github.com/catalystneuro/roiextractors/issues/413. Are you OK with closing this, @pauladkisson ?

**Comment by pauladkisson** [comment]
To my knowledge, we still don't have tests for this, so I wouldn't consider it fixed just yet.

**Comment by h-mayorquin** [comment]
OK, so what kind of test would you need? for someone to produce a set of files where the acquisition cycle does not coincide with the number of pages on the files?

**Comment by pauladkisson** [comment]
> OK, so what kind of test would you need? for someone to produce a set of files where the acquisition cycle does not coincide with the number of pages on the files?

Yes, precisely.

**Comment by h-mayorquin** [comment]
OK. 

For the record, I believe the current extractor handles this well. However, it’s good practice to gather test data for this case and to keep the issue open as a reminder that we don’t yet have such data.

I might ask Jennifer from the Kim lab for example such data.
